title: "Elisa McGhee"
author: "Elisa McGhee"
description: "Colorado State University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true        # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "mcghee_elisacv.pdf", title: CV}
  - {title: "Code", url: "https://}
  - {title: "Blog", file: "/blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:elisa.mcghee@colostate.edu"}
  - {title: Github, icon: github, url: "https://github.com/eamcghee"}
  - {title: Instagram, icon: instagram, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
